version: '3.8' 

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: ./app  
      dockerfile: Dockerfile  
    container_name: flask_app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge

